### ISSUE TITLE
python issues

### ISSUE THREAD

**Issue by Doujinx** [joeyagreco/ranger-reloaded#6]
```
sudo python app.py

Traceback (most recent call last):
  File "/home/kali/Programs/PROJECT HACKINGTOOL/InformationGathering/ranger-reloaded/app.py", line 3, in <module>
    from service.NetworkService import NetworkService
  File "/home/kali/Programs/PROJECT HACKINGTOOL/InformationGathering/ranger-reloaded/service/NetworkService.py", line 5, in <module>
    from ping3 import ping
ModuleNotFoundError: No module named 'ping3'
```

**Comment by joeyagreco** [comment]
Make sure to run

```
pip install -r requirements.txt
```

to install all dependencies.

ping3 is installed [here](https://github.com/joeyagreco/ranger-reloaded/blob/main/requirements.txt).

**Comment by Doujinx** [comment]
Still the same issue. No module ping3, after i run pip install -r requirements.txt and too pip install ping3.
